enum AsyncStorageData {
    USER_ACCESS_TOKEN = "USER_ACCESS_TOKEN",
    USER_REFRESH_TOKEN = "USER_REFRESH_TOKEN",
    CLIENT_ACCESS_TOKEN = "CLIENT_ACCESS_TOKEN",
    CLIENT_REFRESH_TOKEN = "CLIENT_REFRESH_TOKEN",
}

export default AsyncStorageData;
