export enum ServiceCategoryTypes {
    ADOPTION = "Adoção",
    AGED_CARE = "Cuidados com Idosos",
    ALLIED_HEALTH = "Saúde Aliada",
    ALTERNATIVE_COMPLEMENTARY_THERAPIES = "Terapias Alternativas e Complementares",
    CHILD_CARE_KINDERGARTEN = "Cuidado Infantil e/ou Jardim de Infância",
    CHILD_DEVELOPMENT = "Desenvolvimento Infantil",
    CHILD_PROTECTION_FAMILY_SERVICES = "Proteção Infantil e Serviços Familiares",
    COMMUNITY_HEALTH_CARE = "Cuidados de Saúde Comunitária",
    COUNSELLING = "Aconselhamento",
    CRISIS_LINE = "Linha de Crise (uso exclusivo GPAH)",
    DEATH_SERVICES = "Serviços Funerários",
    DENTAL = "Odontologia",
    DISABILITY_SUPPORT = "Apoio à Deficiência",
    DRUG_ALCOHOL = "Drogas/Álcool",
    EDUCATION_LEARNING = "Educação e Aprendizagem",
    EMERGENCY_DEPARTMENT = "Departamento de Emergência",
    EMPLOYMENT = "Emprego",
    FINANCIAL_MATERIAL_AID = "Ajuda Financeira e Material",
    GENERAL_PRACTICE = "Clínica Geral/GP (médico)",
    HOSPITAL = "Hospital",
    HOUSING_HOMELESSNESS = "Habitação/Desabrigados",
    INTERPRETING = "Interpretação",
    JUSTICE = "Justiça",
    LEGAL = "Legal",
    MENTAL_HEALTH = "Saúde Mental",
    PHYSICAL_ACTIVITY_RECREATION = "Atividade Física e Recreação",
    REGULATION = "Regulação",
    RESPITE_CARER_SUPPORT = "Apoio ao Cuidador/Respiro",
    SPECIALIST_CLINICAL_PATHOLOGY = "Patologia Clínica Especializada - requer encaminhamento",
    SPECIALIST_MEDICAL = "Médico Especialista - requer encaminhamento",
    SPECIALIST_OBSTETRICS_GYNECOLOGY = "Obstetrícia e Ginecologia Especializada - requer encaminhamento",
    SPECIALIST_PAEDIATRIC = "Pediatria Especializada - requer encaminhamento",
    SPECIALIST_RADIOLOGY_IMAGING = "Radiologia/Imagem Especializada - requer encaminhamento",
    SPECIALIST_SURGICAL = "Cirurgia Especializada - requer encaminhamento",
    SUPPORT_GROUPS = "Grupos de Apoio",
    TEST_MESSAGE = "Mensagem de Teste (uso exclusivo HSD admin)",
    TRANSPORT = "Transporte",
}

export enum SlotStatus {
    "busy" = "Ocupado",
    "free" = "Livre",
    "busy_unavailable" = "Ocupado/Indisponível",
    "busy_tentative" = "Ocupado/Tentativa",
    "entered_in_error" = "Introduzido por engano",
}
