import { StyleSheet } from "react-native";
import { mix, parseToRgb, rgba } from "polished";
import LightTheme from "@/src/theme/LightTheme";

export const GetSafeAreaBackground = (): [string, string] => [
    LightTheme.colors.primary,
    mix(0.05, LightTheme.colors.white, LightTheme.colors.primary),
];
export const CreateLoginStyles = () =>
    StyleSheet.create({
        container: {
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
            backgroundColor: LightTheme.colors.primary,
            flex: 1,
            fontFamily: "PoppinsRegular",
            paddingTop: 10,
        },
        keyboardAvoidingView: {
            flex: 1,
        },
        scrollViewFormContainer: {
            flexGrow: 1,
            justifyContent: "space-between",
        },
        linearGradient: {
            flex: 1,
        },
        safeAreaContainer: {
            flex: 1,
        },
        header: {
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "baseline",
            paddingHorizontal: 30,
            fontFamily: "PoppinsRegular",
            gap: 10,
            marginBottom: 50,
        },
        logo: {
            width: 155,
            height: 65,
        },
        headerTextContainer: {
            gap: 10,
        },
        title: {
            color: LightTheme.colors.white,
            fontSize: 36,
            fontFamily: "PoppinsRegular",
            display: "flex",
            flexDirection: "row",
            lineHeight: 40,
        },
        titleContainer: {
            textAlign: "left",
            flexDirection: "column",
        },
        subtitleSmall: {
            color: LightTheme.colors.white,
            fontSize: 15,
            fontFamily: "PoppinsRegular",
        },
        formContainer: {
            backgroundColor: mix(0.05, LightTheme.colors.white, LightTheme.colors.primary),
            borderTopStartRadius: 35,
            borderTopEndRadius: 35,
            paddingHorizontal: 35,
            paddingTop: 35,
            flex: 1,
            display: "flex",
            flexDirection: "column",
        },
        label: {
            color: LightTheme.colors.white,
            fontSize: 16,
            marginBottom: 10,
            fontFamily: "PoppinsRegular",
        },
        input: {
            backgroundColor: rgba({ ...parseToRgb(LightTheme.colors.white), alpha: 0.3 }),
            borderRadius: 8,
            paddingVertical: 10,
            paddingHorizontal: 15,
            marginBottom: 15,
            color: LightTheme.colors.white,
            height: 50,
            fontFamily: "PoppinsRegular",
            fontWeight: "500",
            fontSize: 13,
        },
        inputError: {
            borderColor: LightTheme.colors.error,
            borderWidth: 1,
        },
        passwordContainer: {
            position: "relative",
        },
        icon: {
            position: "absolute",
            right: 15,
            top: 14,
        },
        errorContainer: {
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "flex-start",
            gap: 10,
            borderColor: LightTheme.colors.error,
            borderWidth: 1,
            paddingVertical: 5,
            paddingHorizontal: 15,
            borderRadius: 8,
            backgroundColor: LightTheme.colors.secondary,
            marginVertical: 5,
            width: "100%",
        },
        errorIcon: {
            color: LightTheme.colors.error,
        },
        errorText: {
            color: LightTheme.colors.white,
            fontFamily: "PoppinsRegular",
            flex: 1,
            flexWrap: "wrap",
        },
        disabledButton: {
            backgroundColor: rgba({ ...parseToRgb(LightTheme.colors.secondary), alpha: 0.3 }),
            borderColor: LightTheme.colors.secondary,
            borderWidth: 1,
            borderRadius: 8,
            paddingVertical: 10,
            alignItems: "center",
            justifyContent: "center",
            height: 50,
            marginBottom: 10,
            display: "flex",
            flexDirection: "row",
            gap: 10,
        },
        button: {
            backgroundColor: LightTheme.colors.secondary,
            borderColor: LightTheme.colors.secondary,
            color: LightTheme.colors.white,
            borderWidth: 1,
            borderRadius: 8,
            paddingVertical: 10,
            alignItems: "center",
            justifyContent: "center",
            height: 50,
            marginBottom: 10,
            display: "flex",
            flexDirection: "row",
            gap: 10,
        },
        disabledButtonText: {
            color: LightTheme.colors.secondary,
            fontSize: 16,
            fontFamily: "PoppinsRegular",
        },
        buttonText: {
            color: LightTheme.colors.white,
            fontSize: 16,
            fontFamily: "PoppinsRegular",
        },
        linkTextContainer: {
            flexDirection: "row",
            marginTop: 10,
        },
        linkText: {
            color: LightTheme.colors.white,
            textAlign: "left",
            fontFamily: "PoppinsRegular",
        },
        orText: {
            textAlign: "center",
            fontFamily: "PoppinsRegular",
            color: LightTheme.colors.white,
        },
        orTextContainer: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
        },
        orTextLine: {
            flex: 1,
            height: 1,
            backgroundColor: LightTheme.colors.white,
            marginHorizontal: 10,
        },
        socialContainer: {
            flexDirection: "row",
            justifyContent: "center",
            gap: 10,
            width: "100%",
        },
        socialButton: {
            backgroundColor: rgba({ ...parseToRgb(LightTheme.colors.white), alpha: 0.1 }),
            borderRadius: 8,
            padding: 10,
            width: 90,
            display: "flex",
            alignItems: "center",
        },
        registerText: {
            color: LightTheme.colors.white,
            textAlign: "center",
            marginVertical: 20,
            gap: 5,
            display: "flex",
            fontFamily: "PoppinsRegular",
        },
        link: {
            textDecorationLine: "underline",
        },
    });
